# Generated by Django 5.2.7 on 2025-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='week',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='week',
            name='user',
        ),
    ]
