# Generated by Django 5.2.7 on 2025-10-04 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_existing_weeks_to_admin(apps, schema_editor):
    """Assign existing weeks to admin user"""
    Week = apps.get_model('tracker', 'Week')
    User = apps.get_model('auth', 'User')
    
    # Get or create admin user
    admin_user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'email': 'admin@posma-pakpahan.me',
            'is_staff': True,
            'is_superuser': True
        }
    )
    
    # Assign all existing weeks to admin
    Week.objects.filter(user_id__isnull=True).update(user=admin_user)


def reverse_assign_weeks(apps, schema_editor):
    """Remove user assignment from weeks"""
    Week = apps.get_model('tracker', 'Week')
    Week.objects.update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_remove_user_auth'),
    ]

    operations = [
        # Add user field as nullable first
        migrations.AddField(
            model_name='week',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to=settings.AUTH_USER_MODEL),
        ),
        # Run data migration to assign existing weeks to admin
        migrations.RunPython(
            assign_existing_weeks_to_admin,
            reverse_assign_weeks
        ),
        # Make user field non-nullable
        migrations.AlterField(
            model_name='week',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to=settings.AUTH_USER_MODEL),
        ),
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('user', 'start_date')},
        ),
        # Remove old unique constraint on start_date
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(),
        ),
        # Add UserProfile model
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]